---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: {{ .Service }}.{{ .Namespace }}.svc.cluster.local
  namespace: {{ .Namespace }}
spec:
  routes:
  {{ range .Routes -}}
  {{ if .Deprecated -}}
  # Deprecated: RPC {{ .Name }} is deprecated
  {{ end -}}
  - name: {{ .Name }}
    isRetryable: {{ .Retryable }}
    condition:
      method: POST
      pathRegex: {{ .PathRegex }}
  {{ end }}
