// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: testbufile/v1/testbufile.proto

package testbufilev1

import (
	_ "github.com/vic3lord/bufile/proto/bufile/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayRequest) Reset() {
	*x = SayRequest{}
	mi := &file_testbufile_v1_testbufile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayRequest) ProtoMessage() {}

func (x *SayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testbufile_v1_testbufile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayRequest.ProtoReflect.Descriptor instead.
func (*SayRequest) Descriptor() ([]byte, []int) {
	return file_testbufile_v1_testbufile_proto_rawDescGZIP(), []int{0}
}

func (x *SayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayResponse) Reset() {
	*x = SayResponse{}
	mi := &file_testbufile_v1_testbufile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayResponse) ProtoMessage() {}

func (x *SayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testbufile_v1_testbufile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayResponse.ProtoReflect.Descriptor instead.
func (*SayResponse) Descriptor() ([]byte, []int) {
	return file_testbufile_v1_testbufile_proto_rawDescGZIP(), []int{1}
}

func (x *SayResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_testbufile_v1_testbufile_proto protoreflect.FileDescriptor

const file_testbufile_v1_testbufile_proto_rawDesc = "" +
	"\n" +
	"\x1etestbufile/v1/testbufile.proto\x12\rtestbufile.v1\x1a\x16bufile/v1/bufile.proto\" \n" +
	"\n" +
	"SayRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\vSayResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting2[\n" +
	"\x0fGreetingService\x12H\n" +
	"\x03Say\x12\x19.testbufile.v1.SayRequest\x1a\x1a.testbufile.v1.SayResponse\"\n" +
	"\x82\xa6\x1d\x0330s\x90\x02\x02B\xb6\x01\n" +
	"\x11com.testbufile.v1B\x0fTestbufileProtoP\x01Z;github.com/vic3lord/bufile/proto/testbufile/v1;testbufilev1\xa2\x02\x03TXX\xaa\x02\rTestbufile.V1\xca\x02\rTestbufile\\V1\xe2\x02\x19Testbufile\\V1\\GPBMetadata\xea\x02\x0eTestbufile::V1b\x06proto3"

var (
	file_testbufile_v1_testbufile_proto_rawDescOnce sync.Once
	file_testbufile_v1_testbufile_proto_rawDescData []byte
)

func file_testbufile_v1_testbufile_proto_rawDescGZIP() []byte {
	file_testbufile_v1_testbufile_proto_rawDescOnce.Do(func() {
		file_testbufile_v1_testbufile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testbufile_v1_testbufile_proto_rawDesc), len(file_testbufile_v1_testbufile_proto_rawDesc)))
	})
	return file_testbufile_v1_testbufile_proto_rawDescData
}

var file_testbufile_v1_testbufile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testbufile_v1_testbufile_proto_goTypes = []any{
	(*SayRequest)(nil),  // 0: testbufile.v1.SayRequest
	(*SayResponse)(nil), // 1: testbufile.v1.SayResponse
}
var file_testbufile_v1_testbufile_proto_depIdxs = []int32{
	0, // 0: testbufile.v1.GreetingService.Say:input_type -> testbufile.v1.SayRequest
	1, // 1: testbufile.v1.GreetingService.Say:output_type -> testbufile.v1.SayResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testbufile_v1_testbufile_proto_init() }
func file_testbufile_v1_testbufile_proto_init() {
	if File_testbufile_v1_testbufile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testbufile_v1_testbufile_proto_rawDesc), len(file_testbufile_v1_testbufile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testbufile_v1_testbufile_proto_goTypes,
		DependencyIndexes: file_testbufile_v1_testbufile_proto_depIdxs,
		MessageInfos:      file_testbufile_v1_testbufile_proto_msgTypes,
	}.Build()
	File_testbufile_v1_testbufile_proto = out.File
	file_testbufile_v1_testbufile_proto_goTypes = nil
	file_testbufile_v1_testbufile_proto_depIdxs = nil
}
