// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: bufile/v1/bufile.proto

package bufilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_bufile_v1_bufile_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60000,
		Name:          "bufile.v1.linkerd_timeout",
		Tag:           "bytes,60000,opt,name=linkerd_timeout",
		Filename:      "bufile/v1/bufile.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string linkerd_timeout = 60000;
	E_LinkerdTimeout = &file_bufile_v1_bufile_proto_extTypes[0]
)

var File_bufile_v1_bufile_proto protoreflect.FileDescriptor

const file_bufile_v1_bufile_proto_rawDesc = "" +
	"\n" +
	"\x16bufile/v1/bufile.proto\x12\tbufile.v1\x1a google/protobuf/descriptor.proto:I\n" +
	"\x0flinkerd_timeout\x12\x1e.google.protobuf.MethodOptions\x18\xe0\xd4\x03 \x01(\tR\x0elinkerdTimeoutB\x96\x01\n" +
	"\rcom.bufile.v1B\vBufileProtoP\x01Z3github.com/vic3lord/bufile/proto/bufile/v1;bufilev1\xa2\x02\x03BXX\xaa\x02\tBufile.V1\xca\x02\tBufile\\V1\xe2\x02\x15Bufile\\V1\\GPBMetadata\xea\x02\n" +
	"Bufile::V1b\x06proto3"

var file_bufile_v1_bufile_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_bufile_v1_bufile_proto_depIdxs = []int32{
	0, // 0: bufile.v1.linkerd_timeout:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bufile_v1_bufile_proto_init() }
func file_bufile_v1_bufile_proto_init() {
	if File_bufile_v1_bufile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bufile_v1_bufile_proto_rawDesc), len(file_bufile_v1_bufile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_bufile_v1_bufile_proto_goTypes,
		DependencyIndexes: file_bufile_v1_bufile_proto_depIdxs,
		ExtensionInfos:    file_bufile_v1_bufile_proto_extTypes,
	}.Build()
	File_bufile_v1_bufile_proto = out.File
	file_bufile_v1_bufile_proto_goTypes = nil
	file_bufile_v1_bufile_proto_depIdxs = nil
}
